"""Seed data for the GameOps Center demo."""

REGIONS = [
    {
        "id": "cn-east",
        "name": "华东战区",
        "city": "上海",
        "owner": "SRE-A",
        "traffic_weight": 42,
    },
    {
        "id": "cn-north",
        "name": "华北战区",
        "city": "北京",
        "owner": "SRE-B",
        "traffic_weight": 24,
    },
    {
        "id": "cn-south",
        "name": "华南战区",
        "city": "广州",
        "owner": "SRE-C",
        "traffic_weight": 21,
    },
    {
        "id": "ap-sg",
        "name": "东南亚战区",
        "city": "Singapore",
        "owner": "SRE-D",
        "traffic_weight": 13,
    },
]

INITIAL_SERVERS = [
    {
        "id": "cn-east-arena-01",
        "name": "龙渊竞技-01",
        "region": "cn-east",
        "game_mode": "排位竞技",
        "status": "running",
        "version": "v1.8.3",
        "players": 7630,
        "capacity": 9200,
        "cpu": 62.5,
        "memory": 71.2,
        "latency_p95": 58,
        "packet_loss": 0.2,
        "rps": 1460,
        "uptime_hours": 412,
    },
    {
        "id": "cn-east-arena-02",
        "name": "龙渊竞技-02",
        "region": "cn-east",
        "game_mode": "排位竞技",
        "status": "running",
        "version": "v1.8.3",
        "players": 8012,
        "capacity": 9200,
        "cpu": 79.4,
        "memory": 76.8,
        "latency_p95": 71,
        "packet_loss": 0.4,
        "rps": 1588,
        "uptime_hours": 387,
    },
    {
        "id": "cn-east-raid-01",
        "name": "深海副本-01",
        "region": "cn-east",
        "game_mode": "团队副本",
        "status": "running",
        "version": "v1.8.2",
        "players": 3960,
        "capacity": 6400,
        "cpu": 54.1,
        "memory": 64.4,
        "latency_p95": 49,
        "packet_loss": 0.1,
        "rps": 746,
        "uptime_hours": 521,
    },
    {
        "id": "cn-north-arena-01",
        "name": "冰原竞技-01",
        "region": "cn-north",
        "game_mode": "排位竞技",
        "status": "degraded",
        "version": "v1.8.3",
        "players": 6840,
        "capacity": 7600,
        "cpu": 88.7,
        "memory": 84.3,
        "latency_p95": 142,
        "packet_loss": 1.6,
        "rps": 1290,
        "uptime_hours": 278,
    },
    {
        "id": "cn-north-chat-01",
        "name": "冰原聊天-01",
        "region": "cn-north",
        "game_mode": "社交聊天",
        "status": "running",
        "version": "v1.8.3",
        "players": 12120,
        "capacity": 16000,
        "cpu": 45.8,
        "memory": 59.5,
        "latency_p95": 36,
        "packet_loss": 0.2,
        "rps": 2250,
        "uptime_hours": 655,
    },
    {
        "id": "cn-south-raid-01",
        "name": "雨林副本-01",
        "region": "cn-south",
        "game_mode": "团队副本",
        "status": "running",
        "version": "v1.8.3",
        "players": 5140,
        "capacity": 7200,
        "cpu": 57.2,
        "memory": 63.1,
        "latency_p95": 64,
        "packet_loss": 0.5,
        "rps": 892,
        "uptime_hours": 338,
    },
    {
        "id": "cn-south-arena-02",
        "name": "雨林竞技-02",
        "region": "cn-south",
        "game_mode": "排位竞技",
        "status": "running",
        "version": "v1.8.3",
        "players": 7440,
        "capacity": 8200,
        "cpu": 74.9,
        "memory": 82.7,
        "latency_p95": 96,
        "packet_loss": 0.7,
        "rps": 1396,
        "uptime_hours": 219,
    },
    {
        "id": "ap-sg-arena-01",
        "name": "星港竞技-01",
        "region": "ap-sg",
        "game_mode": "排位竞技",
        "status": "running",
        "version": "v1.8.3",
        "players": 4530,
        "capacity": 6000,
        "cpu": 63.2,
        "memory": 67.6,
        "latency_p95": 104,
        "packet_loss": 0.8,
        "rps": 818,
        "uptime_hours": 144,
    },
    {
        "id": "ap-sg-match-01",
        "name": "星港匹配-01",
        "region": "ap-sg",
        "game_mode": "匹配服务",
        "status": "maintenance",
        "version": "v1.8.2",
        "players": 0,
        "capacity": 4000,
        "cpu": 12.3,
        "memory": 38.4,
        "latency_p95": 28,
        "packet_loss": 0.0,
        "rps": 74,
        "uptime_hours": 3,
    },
]

INITIAL_LOGS = [
    {
        "level": "INFO",
        "source": "release-bot",
        "region": "cn-east",
        "server_id": "cn-east-arena-01",
        "message": "完成 v1.8.3 灰度发布健康检查",
    },
    {
        "level": "WARN",
        "source": "alert-manager",
        "region": "cn-north",
        "server_id": "cn-north-arena-01",
        "message": "CPU 连续 3 分钟超过 85%，建议扩容或迁移匹配流量",
    },
    {
        "level": "INFO",
        "source": "match-router",
        "region": "cn-south",
        "server_id": "cn-south-arena-02",
        "message": "南区排位流量权重提升到 21%",
    },
    {
        "level": "ERROR",
        "source": "session-gateway",
        "region": "ap-sg",
        "server_id": "ap-sg-match-01",
        "message": "维护窗口内拒绝新会话，等待发布完成",
    },
]

