"""Seed data for GameOps Center.

The records below are loaded into MySQL on first boot and then become normal
CMDB data.  They model game regions as Kubernetes workloads backed by Docker
images, so the same object can drive monitoring, release, restart, and scaling.
"""

from __future__ import annotations


REGIONS = [
    {
        "id": "cn-east",
        "name": "华东战区",
        "city": "上海",
        "owner": "sre-east",
        "traffic_weight": 42,
    },
    {
        "id": "cn-north",
        "name": "华北战区",
        "city": "北京",
        "owner": "sre-north",
        "traffic_weight": 24,
    },
    {
        "id": "cn-south",
        "name": "华南战区",
        "city": "广州",
        "owner": "sre-south",
        "traffic_weight": 21,
    },
    {
        "id": "ap-sg",
        "name": "新加坡战区",
        "city": "Singapore",
        "owner": "sre-global",
        "traffic_weight": 13,
    },
]


WORKLOADS = [
    {
        "id": "cn-east-arena",
        "name": "华东竞技服",
        "region": "cn-east",
        "game_mode": "排位竞技",
        "deployment": "arena-east",
        "namespace": "game-prod",
        "service": "arena-east-svc",
        "container": "arena",
        "image": "registry.example.com/game/arena:v1.8.3",
        "version": "v1.8.3",
        "replicas": 3,
        "desired_replicas": 3,
        "min_replicas": 2,
        "max_replicas": 8,
        "players": 7630,
        "capacity_per_pod": 3200,
        "cpu": 62.5,
        "memory": 71.2,
        "latency_p95": 58,
        "packet_loss": 0.2,
        "rps": 1460,
        "status": "running",
    },
    {
        "id": "cn-east-raid",
        "name": "华东副本服",
        "region": "cn-east",
        "game_mode": "团队副本",
        "deployment": "raid-east",
        "namespace": "game-prod",
        "service": "raid-east-svc",
        "container": "raid",
        "image": "registry.example.com/game/raid:v1.8.2",
        "version": "v1.8.2",
        "replicas": 2,
        "desired_replicas": 2,
        "min_replicas": 1,
        "max_replicas": 6,
        "players": 3960,
        "capacity_per_pod": 2800,
        "cpu": 54.1,
        "memory": 64.4,
        "latency_p95": 49,
        "packet_loss": 0.1,
        "rps": 746,
        "status": "running",
    },
    {
        "id": "cn-north-arena",
        "name": "华北竞技服",
        "region": "cn-north",
        "game_mode": "排位竞技",
        "deployment": "arena-north",
        "namespace": "game-prod",
        "service": "arena-north-svc",
        "container": "arena",
        "image": "registry.example.com/game/arena:v1.8.3",
        "version": "v1.8.3",
        "replicas": 2,
        "desired_replicas": 2,
        "min_replicas": 2,
        "max_replicas": 8,
        "players": 6840,
        "capacity_per_pod": 3600,
        "cpu": 88.7,
        "memory": 84.3,
        "latency_p95": 142,
        "packet_loss": 1.6,
        "rps": 1290,
        "status": "degraded",
    },
    {
        "id": "cn-north-chat",
        "name": "华北聊天服",
        "region": "cn-north",
        "game_mode": "社交聊天",
        "deployment": "chat-north",
        "namespace": "game-prod",
        "service": "chat-north-svc",
        "container": "chat",
        "image": "registry.example.com/game/chat:v1.8.3",
        "version": "v1.8.3",
        "replicas": 3,
        "desired_replicas": 3,
        "min_replicas": 2,
        "max_replicas": 10,
        "players": 12120,
        "capacity_per_pod": 5600,
        "cpu": 45.8,
        "memory": 59.5,
        "latency_p95": 36,
        "packet_loss": 0.2,
        "rps": 2250,
        "status": "running",
    },
    {
        "id": "cn-south-raid",
        "name": "华南副本服",
        "region": "cn-south",
        "game_mode": "团队副本",
        "deployment": "raid-south",
        "namespace": "game-prod",
        "service": "raid-south-svc",
        "container": "raid",
        "image": "registry.example.com/game/raid:v1.8.3",
        "version": "v1.8.3",
        "replicas": 2,
        "desired_replicas": 2,
        "min_replicas": 1,
        "max_replicas": 6,
        "players": 5140,
        "capacity_per_pod": 3600,
        "cpu": 57.2,
        "memory": 63.1,
        "latency_p95": 64,
        "packet_loss": 0.5,
        "rps": 892,
        "status": "running",
    },
    {
        "id": "cn-south-arena",
        "name": "华南竞技服",
        "region": "cn-south",
        "game_mode": "排位竞技",
        "deployment": "arena-south",
        "namespace": "game-prod",
        "service": "arena-south-svc",
        "container": "arena",
        "image": "registry.example.com/game/arena:v1.8.3",
        "version": "v1.8.3",
        "replicas": 3,
        "desired_replicas": 3,
        "min_replicas": 2,
        "max_replicas": 8,
        "players": 7440,
        "capacity_per_pod": 3000,
        "cpu": 74.9,
        "memory": 82.7,
        "latency_p95": 96,
        "packet_loss": 0.7,
        "rps": 1396,
        "status": "running",
    },
    {
        "id": "ap-sg-arena",
        "name": "新加坡竞技服",
        "region": "ap-sg",
        "game_mode": "排位竞技",
        "deployment": "arena-sg",
        "namespace": "game-prod",
        "service": "arena-sg-svc",
        "container": "arena",
        "image": "registry.example.com/game/arena:v1.8.3",
        "version": "v1.8.3",
        "replicas": 2,
        "desired_replicas": 2,
        "min_replicas": 1,
        "max_replicas": 6,
        "players": 4530,
        "capacity_per_pod": 3000,
        "cpu": 63.2,
        "memory": 67.6,
        "latency_p95": 104,
        "packet_loss": 0.8,
        "rps": 818,
        "status": "running",
    },
    {
        "id": "ap-sg-match",
        "name": "新加坡匹配服",
        "region": "ap-sg",
        "game_mode": "匹配服务",
        "deployment": "match-sg",
        "namespace": "game-prod",
        "service": "match-sg-svc",
        "container": "match",
        "image": "registry.example.com/game/match:v1.8.2",
        "version": "v1.8.2",
        "replicas": 1,
        "desired_replicas": 1,
        "min_replicas": 1,
        "max_replicas": 4,
        "players": 0,
        "capacity_per_pod": 4000,
        "cpu": 12.3,
        "memory": 38.4,
        "latency_p95": 28,
        "packet_loss": 0.0,
        "rps": 74,
        "status": "maintenance",
    },
]


USERS = [
    {
        "username": "admin",
        "password": "admin123",
        "role": "admin",
        "display_name": "平台管理员",
    },
    {
        "username": "release",
        "password": "release123",
        "role": "release_manager",
        "display_name": "发布负责人",
    },
    {
        "username": "viewer",
        "password": "viewer123",
        "role": "observer",
        "display_name": "只读观察员",
    },
]


INITIAL_LOGS = [
    {
        "level": "INFO",
        "source": "release-bot",
        "region": "cn-east",
        "workload_id": "cn-east-arena",
        "message": "完成 v1.8.3 灰度发布后的健康检查",
    },
    {
        "level": "WARN",
        "source": "alert-manager",
        "region": "cn-north",
        "workload_id": "cn-north-arena",
        "message": "CPU 连续 3 分钟超过 85%，建议扩容或迁移匹配流量",
    },
    {
        "level": "INFO",
        "source": "traffic-router",
        "region": "cn-south",
        "workload_id": "cn-south-arena",
        "message": "华南排位流量权重提升到 21%",
    },
    {
        "level": "ERROR",
        "source": "session-gateway",
        "region": "ap-sg",
        "workload_id": "ap-sg-match",
        "message": "维护窗口内拒绝新会话，等待发布完成",
    },
]
